openapi: "3.0.0"
info:
  description: "The interface for the tailscale coordinator server."
  version: "1.0.0"
  title: "Tailscale controlplane API"
  contact:
    email: "contact@tcbv.be"
servers:
  - url: https://login.tailscale.com/
    description: Tailscale production server
paths:
  /key:
    get:
      tags:
      - "key"
      summary: "Get the Wireguard Public Key of the server"
      description: "The control plane is identified with a Wireguard public key. This method fetches the key, encoded as a hex string."
      operationId: "getKey"
      responses:
        "200":
          description: "Success"
          content:
            application/text:
              example: "9e5156a4c65121306dd2d8ed8f92cb8d738e2533011344b522c5d28409bc4970"
              schema:
                $ref: '#/components/schemas/key' 
components:
  schemas:
    key:
      type: "string"
